export const resourceItems = [
  {
    title: "UCF Undergraduate and Graduate Admissions",
    href: "https://www.ucf.edu/admissions/",
    domain: "ucf.edu",
    category: "UCF admissions & programs",
    source: "Official UCF resource",
    description: "Application pathways, requirements, deadlines, and links for prospective undergraduate and graduate students.",
  },
  {
    title: "UCF CECE Graduate Programs",
    href: "https://www.cece.ucf.edu/graduate-programs/",
    domain: "cece.ucf.edu",
    category: "UCF admissions & programs",
    source: "Official UCF resource",
    description: "Master’s and doctoral programs in civil, environmental, and construction engineering.",
  },
  {
    title: "B.S. in Civil Engineering",
    href: "https://www.cece.ucf.edu/bachelor-of-science-in-civil-engineering/",
    domain: "cece.ucf.edu",
    category: "UCF admissions & programs",
    source: "Official UCF resource",
    description: "Overview of UCF’s undergraduate civil engineering program and areas of study.",
  },
  {
    title: "M.S. in Civil Engineering",
    href: "https://www.cece.ucf.edu/master-of-science-in-civil-engineering/",
    domain: "cece.ucf.edu",
    category: "UCF admissions & programs",
    source: "Official UCF resource",
    description: "Degree paths and tracks for graduate study in civil engineering at UCF.",
  },
  {
    title: "Structural and Geotechnical Engineering M.S. Track",
    href: "https://www.ucf.edu/degree/civil-engineering-ms/structural-and-geotechnical-engineering/",
    domain: "ucf.edu",
    category: "UCF admissions & programs",
    source: "Official UCF resource",
    description: "Program details, courses, application requirements, and deadlines for the structural and geotechnical track.",
  },
  {
    title: "Ph.D. in Civil Engineering",
    href: "https://www.cece.ucf.edu/ph-d-in-civil-engineering/",
    domain: "cece.ucf.edu",
    category: "UCF admissions & programs",
    source: "Official UCF resource",
    description: "Research areas, degree requirements, and application information for UCF’s Civil Engineering Ph.D.",
  },
  {
    title: "Accelerated B.S. to M.S. Program",
    href: "https://www.cece.ucf.edu/accelerated-b-s-to-m-s-program/",
    domain: "cece.ucf.edu",
    category: "UCF admissions & programs",
    source: "Official UCF resource",
    description: "A combined degree pathway for eligible UCF undergraduate engineering students.",
  },
  {
    title: "Graduate Application Deadlines and Requirements",
    href: "https://graduate.ucf.edu/application-deadlines-and-requirements/",
    domain: "graduate.ucf.edu",
    category: "UCF admissions & programs",
    source: "Official UCF resource",
    description: "Current UCF graduate application requirements and program-specific deadlines.",
  },
  {
    title: "UCF Office of Undergraduate Research",
    href: "https://academicsuccess.ucf.edu/our/",
    domain: "academicsuccess.ucf.edu",
    category: "Undergraduate research at UCF",
    source: "Official UCF resource",
    description: "Programs, workshops, mentoring, funding, and other support for undergraduate researchers.",
  },
  {
    title: "How to Get Started in Undergraduate Research",
    href: "https://academicsuccess.ucf.edu/our/prospective/how-to-get-started/",
    domain: "academicsuccess.ucf.edu",
    category: "Undergraduate research at UCF",
    source: "Official UCF resource",
    description: "A practical roadmap for finding a topic, faculty mentor, and first research opportunity.",
  },
  {
    title: "UCF Undergraduate Research Opportunities",
    href: "https://academicsuccess.ucf.edu/our/prospective/positions/",
    domain: "academicsuccess.ucf.edu",
    category: "Undergraduate research at UCF",
    source: "Official UCF resource",
    description: "Guidance and listings for students seeking faculty-led research positions.",
  },
  {
    title: "Undergraduate Research Workshops and Deadlines",
    href: "https://academicsuccess.ucf.edu/our/about/calendar/",
    domain: "academicsuccess.ucf.edu",
    category: "Undergraduate research at UCF",
    source: "Official UCF resource",
    description: "Current workshops, information sessions, and research-program deadlines.",
  },
  {
    title: "Summer Undergraduate Research Fellowship",
    href: "https://academicsuccess.ucf.edu/our/summer-undergraduate-research-fellowship/",
    domain: "academicsuccess.ucf.edu",
    category: "Undergraduate research at UCF",
    source: "Official UCF resource",
    description: "UCF summer fellowship information, eligibility, and proposal guidance.",
  },
  {
    title: "Earthquake Seismology Learning Materials",
    href: "http://eqseis.geosc.psu.edu/cammon/index.html",
    domain: "eqseis.geosc.psu.edu",
    category: "Education materials",
    source: "Penn State",
    description: "Foundational notes and exercises covering earthquakes, seismic waves, and seismological analysis.",
  },
  {
    title: "Visible Geology",
    href: "https://app.visiblegeology.com/",
    domain: "app.visiblegeology.com",
    category: "Education materials",
    source: "Visible Geology",
    description: "Interactive tools for visualizing geologic structures, topography, and block models.",
  },
  {
    title: "Engineer4Free: Statics",
    href: "https://www.engineer4free.com/statics.html",
    domain: "engineer4free.com",
    category: "Education materials",
    source: "Engineer4Free",
    description: "Free tutorials and worked examples for core engineering statics concepts.",
  },
  {
    title: "Geospatial Analysis Online",
    href: "https://spatialanalysisonline.com/HTML/index.html",
    domain: "spatialanalysisonline.com",
    category: "Education materials",
    source: "Spatial Analysis Online",
    description: "An open textbook covering spatial data, visualization, statistics, and modeling.",
  },
  {
    title: "Esri MOOCs",
    href: "https://www.esri.com/training/mooc/",
    domain: "esri.com",
    category: "Education materials",
    source: "Esri",
    description: "Free scheduled courses on GIS, spatial analysis, imagery, and location intelligence.",
  },
  {
    title: "NASA ARSET Training",
    href: "https://appliedsciences.nasa.gov/what-we-do/capacity-building/arset",
    domain: "appliedsciences.nasa.gov",
    category: "Education materials",
    source: "NASA",
    description: "Free remote-sensing webinars and applied training using NASA Earth observations.",
  },
  {
    title: "Dive into Deep Learning",
    href: "https://d2l.ai/",
    domain: "d2l.ai",
    category: "Education materials",
    source: "Open textbook",
    description: "An interactive open textbook with code, mathematics, and practical deep-learning examples.",
  },
  {
    title: "Interpretable Machine Learning",
    href: "https://christophm.github.io/interpretable-ml-book/",
    domain: "christophm.github.io",
    category: "Education materials",
    source: "Open textbook",
    description: "A clear introduction to methods for explaining and interpreting machine-learning models.",
  },
  {
    title: "Google Earth Engine",
    href: "https://developers.google.com/earth-engine",
    domain: "developers.google.com",
    category: "Research tools & data",
    source: "Google for Developers",
    description: "Documentation and tutorials for planetary-scale geospatial analysis in the cloud.",
  },
  {
    title: "USGS EarthExplorer",
    href: "https://earthexplorer.usgs.gov/",
    domain: "earthexplorer.usgs.gov",
    category: "Research tools & data",
    source: "U.S. Geological Survey",
    description: "Search and download satellite imagery, aerial photography, elevation, and other Earth-science data.",
  },
  {
    title: "Sentinel Hub EO Browser",
    href: "https://apps.sentinel-hub.com/eo-browser/",
    domain: "apps.sentinel-hub.com",
    category: "Research tools & data",
    source: "Sentinel Hub",
    description: "Explore, compare, and visualize Sentinel and other Earth-observation imagery.",
  },
  {
    title: "QGIS",
    href: "https://qgis.org/",
    domain: "qgis.org",
    category: "Research tools & data",
    source: "QGIS project",
    description: "Open-source desktop GIS for mapping, spatial analysis, and geospatial data management.",
  },
  {
    title: "OpenTopography",
    href: "https://opentopography.org/",
    domain: "opentopography.org",
    category: "Research tools & data",
    source: "OpenTopography",
    description: "Access high-resolution topography data, processing tools, and educational resources.",
  },
  {
    title: "DesignSafe-CI",
    href: "https://www.designsafe-ci.org/",
    domain: "designsafe-ci.org",
    category: "Research tools & data",
    source: "NSF NHERI",
    description: "Data, computing, collaboration, and learning tools for natural-hazards engineering research.",
  },
  {
    title: "VOSviewer",
    href: "https://www.vosviewer.com/",
    domain: "vosviewer.com",
    category: "Research writing & discovery",
    source: "Leiden University",
    description: "Build and explore bibliometric networks for literature reviews and research mapping.",
  },
  {
    title: "OpenAlex",
    href: "https://openalex.org/",
    domain: "openalex.org",
    category: "Research writing & discovery",
    source: "OurResearch",
    description: "An open catalog of scholarly works, authors, institutions, topics, and citations.",
  },
  {
    title: "Zotero",
    href: "https://www.zotero.org/",
    domain: "zotero.org",
    category: "Research writing & discovery",
    source: "Zotero",
    description: "Free reference management for collecting, organizing, citing, and sharing research sources.",
  },
  {
    title: "Overleaf",
    href: "https://www.overleaf.com/",
    domain: "overleaf.com",
    category: "Research writing & discovery",
    source: "Overleaf",
    description: "Collaborative online LaTeX writing for papers, reports, theses, and presentations.",
  },
] as const;
